//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBBO_UI {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Button button1;
        
        protected System.Web.UI.WebControls.Label lbltext;
        
        protected System.Web.UI.WebControls.TextBox txtTicker;
        
        protected System.Web.UI.WebControls.Label lblError;
        
        protected System.Web.UI.WebControls.Button buttonFetch;
        
        protected System.Web.UI.WebControls.DataGrid dgDataGrid;
        
        protected System.Web.UI.WebControls.DataGrid dgNBBOGrid;
    }
}
